-- Create leagues table
CREATE TABLE leagues (
    id SERIAL PRIMARY KEY,
    league_key VARCHAR(255) NOT NULL UNIQUE,
    league_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    url TEXT,
    draft_status VARCHAR(50),
    num_teams INTEGER,
    league_update_timestamp TIMESTAMP,
    scoring_type VARCHAR(50),
    current_week INTEGER,
    end_week INTEGER,
    is_finished BOOLEAN,
    logo_url TEXT,
    short_invitation_url TEXT,
    league_type VARCHAR(50),
    renew VARCHAR(50),
    renewed VARCHAR(50),
    game_code VARCHAR(50),
    is_cash_league BOOLEAN,
    is_plus_league BOOLEAN,
    is_pro_league BOOLEAN,
    season INTEGER,
    start_date DATE,
    start_week INTEGER,
    felo_tier VARCHAR(50),
    end_date DATE,
    weekly_deadline VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);