-- `GENERATED ALWAYS AS IDENTITY` rejects any explicit value for the column,
-- even inside an upsert whose ON CONFLICT branch would just update the row.
-- The commissioner settings UI re-sends a row's own `id` when saving an
-- edit (fetched from a prior GET), which upserts teams/league_settings and
-- hit exactly this: "cannot insert a non-DEFAULT value into column id".
-- `GENERATED BY DEFAULT AS IDENTITY` keeps the same auto-increment behavior
-- for inserts that omit id, while allowing upserts that include it.

ALTER TABLE public.leagues ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.league_settings ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.teams ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.team_members ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.players ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.picks ALTER COLUMN id SET GENERATED BY DEFAULT;
